- name: "Creating a windows server with one playbook"
  hosts: winServers
  tasks:
  - name: Changes the hostname to winHomeServer1
    ansible.windows.win_hostname:
      name: winHomeServer1
    register: res

  - name: Set up static IP address
    win_shell: "Get-NetIpAddress -InterfaceAlias 'Ethernet*' | New-NetIpAddress -IpAddress 192.168.73.11 -PrefixLength 24 -DefaultGateway 192.168.73.1"
    async: 100 
    poll: 0
  
  - name: Install AD DS role
    ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
  - name: Promote server to Domain Controller
    ansible.windows.win_shell:
        command: |
          Import-Module ADDSDeployment
          Install-ADDSForest `
            -DomainName "xiam.bl" `
            -SafeModeAdministratorPassword "Xiam2007!"
            -Force
